#!/usr/bin/env python3
"""
Top conference paper search script
Uses DBLP API to fetch paper lists + Semantic Scholar API to supplement citation counts and abstracts
Supports top conferences: CVPR/ICCV/ECCV/ICLR/AAAI/NeurIPS/ICML
"""

import json
import os
import re
import sys
import time
import logging
import argparse
from typing import List, Dict, Optional, Tuple
import urllib.request
import urllib.parse

logger = logging.getLogger(__name__)


def title_to_note_filename(title: str) -> str:
    """Convert paper title to Obsidian note filename (consistent with generate_note.py).

    Uses the exact same rules as paper-analyze/scripts/generate_note.py,
    ensuring wikilink paths generated by conf-papers correctly point to files created by paper-analyze.
    """
    filename = re.sub(r'[ /\\:*?"<>|]+', '_', title).strip('_')
    return filename

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False
    logger.warning("requests library not found, using urllib")

# ---------------------------------------------------------------------------
# Reuse scoring functions from search_arxiv.py
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_START_MY_DAY_SCRIPTS = os.path.join(os.path.dirname(os.path.dirname(_SCRIPT_DIR)), 'start-my-day', 'scripts')
if _START_MY_DAY_SCRIPTS not in sys.path:
    sys.path.insert(0, _START_MY_DAY_SCRIPTS)

from search_arxiv import (
    calculate_relevance_score,
    calculate_quality_score,
    SCORE_MAX,
    RELEVANCE_TITLE_KEYWORD_BOOST,
    RELEVANCE_SUMMARY_KEYWORD_BOOST,
    RELEVANCE_CATEGORY_MATCH_BOOST,
    S2_RATE_LIMIT_WAIT,
)

# ---------------------------------------------------------------------------
# Conference Configuration
# ---------------------------------------------------------------------------
# DBLP toc key mapping: used for toc:db/conf/... query format
# value = (conf_path, toc_name_template)
# {year} in toc_name_template is replaced with the actual year
# For conferences where toc query is unavailable (e.g., ECCV), use venue+year fallback query
DBLP_VENUES = {
    "CVPR": {"toc": "conf/cvpr", "toc_name": "cvpr{year}"},
    "ICCV": {"toc": "conf/iccv", "toc_name": "iccv{year}"},
    "ECCV": {"toc": "conf/eccv", "toc_name": None, "venue_query": "ECCV"},  # ECCV toc unavailable, use venue+year
    "ICLR": {"toc": "conf/iclr", "toc_name": "iclr{year}"},
    "AAAI": {"toc": "conf/aaai", "toc_name": "aaai{year}"},
    "NeurIPS": {"toc": "conf/nips", "toc_name": "neurips{year}"},
    "ICML": {"toc": "conf/icml", "toc_name": "icml{year}"},
}

# Conference -> arXiv category mapping (for category match bonus in relevance scoring)
VENUE_TO_CATEGORIES = {
    "CVPR": ["cs.CV"],
    "ICCV": ["cs.CV"],
    "ECCV": ["cs.CV"],
    "ICLR": ["cs.LG", "cs.AI"],
    "ICML": ["cs.LG"],
    "NeurIPS": ["cs.LG", "cs.AI", "cs.CL"],
    "AAAI": ["cs.AI"],
}

# Scoring weights (recency dimension removed since year is specified by user)
WEIGHTS_CONF = {
    'relevance': 0.40,
    'popularity': 0.40,
    'quality': 0.20,
}

# Popularity: full score baseline for influential citations
POPULARITY_INFLUENTIAL_CITATION_FULL_SCORE = 100

# Semantic Scholar Configuration
S2_API_URL = "https://api.semanticscholar.org/graph/v1/paper/search"
S2_PAPER_URL = "https://api.semanticscholar.org/graph/v1/paper"
S2_FIELDS = "title,abstract,citationCount,influentialCitationCount,externalIds,url,authors"
S2_BATCH_URL = "https://api.semanticscholar.org/graph/v1/paper/batch"
S2_API_KEY = None

# DBLP API Configuration
DBLP_API_URL = "https://dblp.org/search/publ/api"

# ---------------------------------------------------------------------------
# DBLP Search
# ---------------------------------------------------------------------------

def search_dblp_conference(venue_key: str, year: int, max_results: int = 1000, max_retries: int = 3) -> List[Dict]:
    """
    Search papers for a specific conference and year using DBLP Search API

    Args:
        venue_key: Conference name (e.g., "CVPR")
        year: Year
        max_results: Maximum number of results
        max_retries: Maximum number of retries

    Returns:
        List of papers, each containing title, authors, dblp_url, year, conference
    """
    venue_info = DBLP_VENUES.get(venue_key)
    if not venue_info:
        logger.warning("[DBLP] Unknown venue: %s", venue_key)
        return []

    papers = []
    hits_fetched = 0
    batch_size = min(max_results, 1000)

    # Build query list: prefer toc format, fallback to venue+year
    queries_to_try = []
    toc_name = venue_info.get("toc_name")
    if toc_name:
        toc_path = venue_info["toc"]
        queries_to_try.append(f"toc:db/{toc_path}/{toc_name.format(year=year)}.bht:")
    # Always add venue+year as fallback
    venue_query = venue_info.get("venue_query", venue_key)
    queries_to_try.append(f"venue:{venue_query} year:{year}")

    for query_str in queries_to_try:
        papers = []
        hits_fetched = 0
        query_failed = False

        while hits_fetched < max_results:
            params = {
                "q": query_str,
                "format": "json",
                "h": batch_size,
                "f": hits_fetched,
            }

            url = f"{DBLP_API_URL}?{urllib.parse.urlencode(params)}"
            logger.info("[DBLP] Searching %s %d (offset=%d, query=%s)", venue_key, year, hits_fetched, query_str[:60])

            success = False
            for attempt in range(max_retries):
                try:
                    if HAS_REQUESTS:
                        resp = requests.get(url, headers={"User-Agent": "ConfPapers/1.0"}, timeout=60)
                        resp.raise_for_status()
                        data = resp.json()
                    else:
                        req = urllib.request.Request(url, headers={"User-Agent": "ConfPapers/1.0"})
                        with urllib.request.urlopen(req, timeout=60) as response:
                            data = json.loads(response.read().decode('utf-8'))

                    result = data.get("result", {})
                    hits = result.get("hits", {})
                    total = int(hits.get("@total", 0))
                    hit_list = hits.get("hit", [])

                    if not hit_list:
                        logger.info("[DBLP] %s %d: no more results (total=%d)", venue_key, year, total)
                        if papers:
                            logger.info("[DBLP] %s %d: found %d papers", venue_key, year, len(papers))
                            return papers
                        # 0 results with this query, try next
                        query_failed = True
                        break

                    for hit in hit_list:
                        info = hit.get("info", {})
                        title = info.get("title", "").rstrip(".")
                        if not title:
                            continue

                        authors_info = info.get("authors", {}).get("author", [])
                        if isinstance(authors_info, dict):
                            authors_info = [authors_info]
                        authors = [a.get("text", "") for a in authors_info if a.get("text")]

                        paper = {
                            "title": title,
                            "authors": authors,
                            "dblp_url": info.get("url", ""),
                            "year": int(info.get("year", year)),
                            "conference": venue_key,
                            "doi": info.get("doi", ""),
                            "venue": info.get("venue", venue_key),
                            "source": "dblp",
                        }
                        papers.append(paper)

                    hits_fetched += len(hit_list)
                    success = True

                    if hits_fetched >= total or hits_fetched >= max_results:
                        break

                    time.sleep(1)
                    break  # Success, exit retry loop

                except Exception as e:
                    logger.warning("[DBLP] Error (attempt %d/%d): %s", attempt + 1, max_retries, e)
                    if attempt < max_retries - 1:
                        wait_time = (2 ** attempt) * 3
                        logger.info("[DBLP] Retrying in %d seconds...", wait_time)
                        time.sleep(wait_time)
                    else:
                        logger.warning("[DBLP] Query failed for %s: %s", venue_key, query_str[:60])
                        query_failed = True

            if query_failed:
                break
            if hits_fetched >= max_results:
                break

        if papers:
            logger.info("[DBLP] %s %d: found %d papers", venue_key, year, len(papers))
            return papers
        elif query_failed:
            logger.info("[DBLP] Trying fallback query for %s %d...", venue_key, year)
            continue

    logger.warning("[DBLP] %s %d: no papers found with any query", venue_key, year)
    return []


def search_all_conferences(year: int, venues: List[str], max_per_venue: int = 1000) -> List[Dict]:
    """
    Search papers across all conferences, merge and deduplicate

    Args:
        year: Year
        venues: List of conferences
        max_per_venue: Maximum papers to fetch per venue

    Returns:
        Deduplicated list of papers
    """
    all_papers = []
    seen_titles = set()

    for venue in venues:
        logger.info("=" * 50)
        logger.info("Searching %s %d...", venue, year)

        papers = search_dblp_conference(venue, year, max_results=max_per_venue)

        for p in papers:
            title_norm = re.sub(r'[^a-z0-9\s]', '', p['title'].lower()).strip()
            if title_norm not in seen_titles:
                seen_titles.add(title_norm)
                all_papers.append(p)

        logger.info("Total unique papers so far: %d", len(all_papers))
        time.sleep(1)  # Delay between conferences

    return all_papers


# ---------------------------------------------------------------------------
# Two-stage filtering: Stage 1 - Lightweight keyword filtering
# ---------------------------------------------------------------------------

def load_conf_papers_config(config_path: str) -> Dict:
    """
    Load dedicated configuration from conf-papers.yaml.

    Args:
        config_path: Path to conf-papers.yaml

    Returns:
        {keywords: [...], excluded_keywords: [...], default_year, default_conferences, top_n}
    """
    import yaml

    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            cp = yaml.safe_load(f) or {}
    except Exception as e:
        logger.error("Error loading conf-papers config: %s", e)
        cp = {}

    return {
        'keywords': cp.get('keywords', []),
        'excluded_keywords': cp.get('excluded_keywords', []),
        'default_year': cp.get('default_year'),
        'default_conferences': cp.get('default_conferences'),
        'top_n': cp.get('top_n', 10),
    }


def lightweight_keyword_filter(papers: List[Dict], cp_config: Dict) -> List[Dict]:
    """
    Stage 1: Lightweight relevance filtering based on title keywords only
    Uses keywords from conf-papers.yaml

    Args:
        papers: All papers fetched from DBLP
        cp_config: conf-papers dedicated config

    Returns:
        List of papers that passed keyword filtering
    """
    # Collect all keywords (lowercase)
    all_keywords = set(kw.lower() for kw in cp_config['keywords'])
    excluded_lower = set(kw.lower() for kw in cp_config['excluded_keywords'])

    filtered = []
    for paper in papers:
        title_lower = paper['title'].lower()

        # Check excluded keywords
        if any(ex in title_lower for ex in excluded_lower):
            continue

        # Check if it matches any research keywords
        matched = False
        matched_keywords = []
        for kw in all_keywords:
            if kw in title_lower:
                matched = True
                matched_keywords.append(kw)

        if matched:
            paper['_preliminary_keywords'] = matched_keywords
            filtered.append(paper)

    logger.info("[Filter] Lightweight keyword filter: %d -> %d papers", len(papers), len(filtered))
    return filtered


# ---------------------------------------------------------------------------
# Semantic Scholar Enrichment
# ---------------------------------------------------------------------------

def title_similarity(a: str, b: str) -> float:
    """
    Normalized title comparison for S2 match verification

    Returns:
        Similarity score between 0.0 and 1.0
    """
    def normalize(s):
        return re.sub(r'[^a-z0-9\s]', '', s.lower()).strip()

    a_norm = normalize(a)
    b_norm = normalize(b)

    if not a_norm or not b_norm:
        return 0.0

    # Use word-level Jaccard similarity
    words_a = set(a_norm.split())
    words_b = set(b_norm.split())

    if not words_a or not words_b:
        return 0.0

    intersection = words_a & words_b
    union = words_a | words_b

    return len(intersection) / len(union)


def enrich_with_semantic_scholar(papers: List[Dict], max_retries: int = 3) -> List[Dict]:
    """
    Use S2 Search API to supplement abstract/citations/arxiv_id by title
    Process in batches with intervals to avoid rate limiting

    Args:
        papers: List of papers needing enrichment
        max_retries: Maximum retries per request

    Returns:
        List of papers with supplemented information
    """
    if not HAS_REQUESTS:
        logger.warning("[S2] requests library not available, skipping enrichment")
        for p in papers:
            p['abstract'] = None
            p['citationCount'] = 0
            p['influentialCitationCount'] = 0
            p['s2_matched'] = False
        return papers

    headers = {"User-Agent": "ConfPapers/1.0"}
    if S2_API_KEY:
        headers["x-api-key"] = S2_API_KEY

    enriched_count = 0
    total = len(papers)

    for i, paper in enumerate(papers):
        title = paper.get('title', '')
        if not title:
            paper['abstract'] = None
            paper['citationCount'] = 0
            paper['influentialCitationCount'] = 0
            paper['s2_matched'] = False
            continue

        if (i + 1) % 10 == 0:
            logger.info("[S2] Progress: %d/%d enriched so far: %d", i + 1, total, enriched_count)

        params = {
            "query": title,
            "limit": 3,
            "fields": S2_FIELDS,
        }

        matched = False
        for attempt in range(max_retries):
            try:
                response = requests.get(S2_API_URL, params=params, headers=headers, timeout=15)
                if response.status_code == 429:
                    wait = S2_RATE_LIMIT_WAIT
                    logger.warning("[S2] Rate limit hit, waiting %d seconds...", wait)
                    time.sleep(wait)
                    continue
                response.raise_for_status()
                data = response.json()

                results = data.get("data", [])
                if not results:
                    break

                best_match = None
                best_sim = 0.0
                for r in results:
                    sim = title_similarity(title, r.get('title', ''))
                    if sim > best_sim:
                        best_sim = sim
                        best_match = r

                if best_match and best_sim >= 0.6:
                    paper['abstract'] = best_match.get('abstract')
                    paper['citationCount'] = best_match.get('citationCount') or 0
                    paper['influentialCitationCount'] = best_match.get('influentialCitationCount') or 0
                    paper['s2_url'] = best_match.get('url', '')

                    ext_ids = best_match.get('externalIds', {})
                    if ext_ids:
                        paper['arxiv_id'] = ext_ids.get('ArXiv')
                        paper['doi'] = paper.get('doi') or ext_ids.get('DOI', '')

                    if not paper.get('authors') and best_match.get('authors'):
                        paper['authors'] = [a.get('name', '') for a in best_match['authors'] if a.get('name')]

                    paper['s2_matched'] = True
                    paper['s2_title_similarity'] = round(best_sim, 2)
                    enriched_count += 1
                    matched = True

                break

            except Exception as e:
                error_msg = str(e)
                is_rate_limit = "429" in error_msg or "Too Many Requests" in error_msg
                if attempt < max_retries - 1:
                    if is_rate_limit:
                        time.sleep(S2_RATE_LIMIT_WAIT)
                    else:
                        time.sleep(2 ** attempt)
                else:
                    logger.debug("[S2] Failed to enrich: %s", title[:50])

        if not matched:
            paper['abstract'] = None
            paper['citationCount'] = 0
            paper['influentialCitationCount'] = 0
            paper['s2_matched'] = False

        # Important: wait 1 second after each request to avoid 429
        # S2 free tier allows ~1 req/sec
        time.sleep(1.0)

    logger.info("[S2] Enrichment complete: %d/%d papers enriched", enriched_count, total)
    return papers


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def calculate_popularity_score(paper: Dict) -> float:
    """
    Calculate popularity based on influentialCitationCount and citationCount

    Args:
        paper: Paper information

    Returns:
        Popularity score (0-SCORE_MAX)
    """
    inf_cit = paper.get('influentialCitationCount', 0)
    cit = paper.get('citationCount', 0)

    if inf_cit > 0:
        # Influential citations: normalize to 0-SCORE_MAX
        score = min(inf_cit / (POPULARITY_INFLUENTIAL_CITATION_FULL_SCORE / SCORE_MAX), SCORE_MAX)
    elif cit > 0:
        # Regular citations: more conservative scoring
        score = min(cit / 200 * SCORE_MAX, SCORE_MAX * 0.7)
    else:
        score = 0.0

    return score


def filter_and_score_papers(papers: List[Dict], cp_config: Dict, top_n: int = 10) -> List[Dict]:
    """
    Perform full three-dimensional scoring (relevance + popularity + quality), sort and take top N
    Build virtual domain from conf-papers.yaml keywords for scoring

    Args:
        papers: List of papers (already enriched by S2)
        cp_config: conf-papers dedicated config
        top_n: Return top N papers

    Returns:
        Scored and sorted list of papers
    """
    # Build virtual domain for calculate_relevance_score
    domains = {
        "conf_papers": {
            "keywords": cp_config['keywords'],
            "arxiv_categories": ["cs.AI", "cs.CL", "cs.LG"],
        }
    }
    excluded_keywords = cp_config['excluded_keywords']

    scored_papers = []

    for paper in papers:
        # To reuse calculate_relevance_score, supplement categories for conference papers
        # Use conference-to-category mapping
        venue = paper.get('conference', '')
        venue_categories = VENUE_TO_CATEGORIES.get(venue, [])
        paper['categories'] = venue_categories

        # Use abstract as summary (compatible with calculate_relevance_score)
        if paper.get('abstract') and not paper.get('summary'):
            paper['summary'] = paper['abstract']

        # Calculate relevance
        relevance, matched_domain, matched_keywords = calculate_relevance_score(
            paper, domains, excluded_keywords
        )

        if relevance == 0:
            continue

        # Calculate popularity
        popularity = calculate_popularity_score(paper)

        # Calculate quality
        summary = paper.get('summary', '') or paper.get('abstract', '') or ''
        quality = calculate_quality_score(summary)

        # Calculate composite score (three dimensions)
        normalized = {
            'relevance': (relevance / SCORE_MAX) * 10,
            'popularity': (popularity / SCORE_MAX) * 10,
            'quality': (quality / SCORE_MAX) * 10,
        }
        final_score = sum(normalized[k] * WEIGHTS_CONF[k] for k in WEIGHTS_CONF)
        final_score = round(final_score, 2)

        paper['scores'] = {
            'relevance': round(relevance, 2),
            'popularity': round(popularity, 2),
            'quality': round(quality, 2),
            'recommendation': final_score,
        }
        paper['matched_domain'] = matched_domain
        paper['matched_keywords'] = matched_keywords

        scored_papers.append(paper)

    # Sort by recommendation score
    scored_papers.sort(key=lambda x: x['scores']['recommendation'], reverse=True)

    logger.info("[Score] %d papers scored, returning top %d", len(scored_papers), top_n)
    return scored_papers[:top_n]


# ---------------------------------------------------------------------------
# Main function
# ---------------------------------------------------------------------------

def main():
    # Default config path: conf-papers.yaml in the skill directory
    default_config = os.path.join(os.path.dirname(_SCRIPT_DIR), 'conf-papers.yaml')

    parser = argparse.ArgumentParser(description='Search top conference papers via DBLP + Semantic Scholar')
    parser.add_argument('--config', type=str,
                        default=default_config,
                        help='Path to conf-papers.yaml config file')
    parser.add_argument('--output', type=str, default='conf_papers_filtered.json',
                        help='Output JSON file path')
    parser.add_argument('--year', type=int, default=None,
                        help='Conference year to search (default: from config)')
    parser.add_argument('--conferences', type=str, default=None,
                        help='Comma-separated conference names (default: from config)')
    parser.add_argument('--top-n', type=int, default=None,
                        help='Number of top papers to return (default: from config)')
    parser.add_argument('--max-per-venue', type=int, default=1000,
                        help='Max papers to fetch per venue from DBLP')
    parser.add_argument('--skip-enrichment', action='store_true',
                        help='Skip Semantic Scholar enrichment (for debugging)')

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s',
        datefmt='%H:%M:%S',
        stream=sys.stderr,
    )

    if not os.path.exists(args.config):
        logger.error("Config file not found: %s", args.config)
        return 1

    logger.info("Loading conf-papers config from: %s", args.config)
    cp_config = load_conf_papers_config(args.config)
    logger.info("Config: %d keywords, %d excluded",
                len(cp_config['keywords']), len(cp_config['excluded_keywords']))

    # Determine year: CLI > config > error
    year = args.year or cp_config.get('default_year')
    if not year:
        logger.error("Search year not specified. Please set it via --year argument or conf_papers.default_year in the config file.")
        return 1

    # Determine top_n: CLI > config > default 10
    top_n = args.top_n or cp_config.get('top_n', 10)

    # Determine conferences to search: CLI > config > all 7
    if args.conferences:
        venues = [v.strip() for v in args.conferences.split(',')]
    elif cp_config.get('default_conferences'):
        venues = list(cp_config['default_conferences'])
    else:
        venues = list(DBLP_VENUES.keys())

    # Validate conference names (case-insensitive matching)
    venue_name_map = {k.upper(): k for k in DBLP_VENUES}
    valid_venues = []
    for v in venues:
        canonical = venue_name_map.get(v.upper())
        if canonical:
            valid_venues.append(canonical)
        else:
            logger.warning("Unknown conference: %s (available: %s)", v, ', '.join(DBLP_VENUES.keys()))
    venues = valid_venues

    if not venues:
        logger.error("No valid conferences specified")
        return 1

    logger.info("Conferences: %s", ', '.join(venues))
    logger.info("Year: %d", year)

    # ========== Step 1: DBLP Search ==========
    logger.info("=" * 70)
    logger.info("Step 1: Searching papers from DBLP")
    logger.info("=" * 70)

    all_papers = search_all_conferences(year, venues, max_per_venue=args.max_per_venue)
    total_found = len(all_papers)
    logger.info("Total papers found from DBLP: %d", total_found)

    if not all_papers:
        logger.warning("No papers found from DBLP!")
        # Output empty results
        output = {
            "year": year,
            "conferences_searched": venues,
            "total_found": 0,
            "total_enriched": 0,
            "total_unique": 0,
            "top_papers": [],
        }
        with open(args.output, 'w', encoding='utf-8') as f:
            json.dump(output, f, ensure_ascii=False, indent=2)
        print(json.dumps(output, ensure_ascii=False, indent=2))
        return 0

    # ========== Step 2: Lightweight Keyword Filtering ==========
    logger.info("=" * 70)
    logger.info("Step 2: Lightweight keyword filtering")
    logger.info("=" * 70)

    filtered_papers = lightweight_keyword_filter(all_papers, cp_config)
    total_filtered = len(filtered_papers)

    if not filtered_papers:
        logger.warning("No papers passed keyword filter!")
        output = {
            "year": year,
            "conferences_searched": venues,
            "total_found": total_found,
            "total_enriched": 0,
            "total_unique": 0,
            "top_papers": [],
        }
        with open(args.output, 'w', encoding='utf-8') as f:
            json.dump(output, f, ensure_ascii=False, indent=2)
        print(json.dumps(output, ensure_ascii=False, indent=2))
        return 0

    # ========== Step 3: Semantic Scholar Enrichment ==========
    total_enriched = 0
    if not args.skip_enrichment:
        logger.info("=" * 70)
        logger.info("Step 3: Enriching with Semantic Scholar (%d papers)", len(filtered_papers))
        logger.info("=" * 70)

        filtered_papers = enrich_with_semantic_scholar(filtered_papers)
        total_enriched = sum(1 for p in filtered_papers if p.get('s2_matched'))
    else:
        logger.info("Skipping Semantic Scholar enrichment (--skip-enrichment)")

    # ========== Step 4: Scoring and Ranking ==========
    logger.info("=" * 70)
    logger.info("Step 4: Scoring and ranking")
    logger.info("=" * 70)

    top_papers = filter_and_score_papers(filtered_papers, cp_config, top_n=top_n)

    # Clean internal fields from output
    for p in top_papers:
        p.pop('_preliminary_keywords', None)
        p.pop('s2_matched', None)
        p.pop('s2_title_similarity', None)
        p.pop('categories', None)
        p.pop('summary', None)  # Keep abstract, remove duplicate summary
        # Add note_filename to each paper, consistent with generate_note.py filename rules
        # So wikilinks generated by conf-papers can directly use this field
        p['note_filename'] = title_to_note_filename(p.get('title', ''))

    # Prepare output
    output = {
        "year": args.year,
        "conferences_searched": venues,
        "total_found": total_found,
        "total_filtered": total_filtered,
        "total_enriched": total_enriched,
        "top_papers": top_papers,
    }

    with open(args.output, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2, default=str)

    logger.info("Results saved to: %s", args.output)
    logger.info("Top %d papers:", len(top_papers))
    for i, p in enumerate(top_papers, 1):
        cit = p.get('citationCount', 0)
        logger.info("  %d. [%s] %s... (Score: %s, Citations: %d)",
                     i, p.get('conference', '?'), p.get('title', 'N/A')[:50],
                     p['scores']['recommendation'], cit)

    print(json.dumps(output, ensure_ascii=False, indent=2, default=str))
    return 0


if __name__ == '__main__':
    sys.exit(main())
